"""Regenerate `golden.json` from `corpus.json` using the pinned oracle.

Run from the Python oracle checkout:

    PYTHONPATH=src ./.venv/Scripts/python.exe \
      <worktree>/probes/fnmatch/generate-golden.py <worktree>/probes/fnmatch

The golden records `fnmatch.fnmatchcase`'s verdict for every pair, plus the
`fnmatch.translate` source, so a divergence points at which rule drifted rather
than only that one did.
"""

from __future__ import annotations

import fnmatch
import json
import sys
from pathlib import Path


def main() -> int:
    probe_dir = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).parent)
    corpus = json.loads((probe_dir / "corpus.json").read_text(encoding="utf-8"))
    golden = {
        "comment": "Generated by generate-golden.py from the pinned Python oracle. Do not hand-edit.",
        "results": [
            {
                "name": name,
                "pattern": pattern,
                "matches": fnmatch.fnmatchcase(name, pattern),
                "translate": fnmatch.translate(pattern),
            }
            for name, pattern in corpus["pairs"]
        ],
    }
    (probe_dir / "golden.json").write_text(
        json.dumps(golden, indent=2) + "\n", encoding="utf-8"
    )
    mismatches = sum(1 for row in golden["results"] if row["matches"])
    print(f"wrote {len(golden['results'])} rows ({mismatches} matching)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
