/**
 * Bake the OWL 2 RL ruleset into a TypeScript constant.
 *
 * `rdfjs-inference-engine` reads its bundled ruleset from
 * `rules/owl2rl/owl2rl-eyeling.n3` on disk. The ADR ships the engine as a
 * `deno compile` binary, and the reasoning spike verified the failure mode that
 * matters: a precompiled *runtime* constructor swallows the baked background
 * facts, while embedding the rule *text* and calling `load()` reproduces the
 * full closure with no filesystem access at all (clean-room verified from a
 * bare temp directory).
 *
 * So the ruleset is text, generated from the installed package, and checked in
 * — regenerating it is this script's whole job:
 *
 * ```sh
 * deno task bake:rules
 * ```
 *
 * The output is a single template literal, so the escaping here is the whole
 * risk: a backslash, a backtick or a `${` in the ruleset would otherwise end
 * the literal early or interpolate.
 */

const rulesPath = Deno.args[0] ??
  "node_modules/rdfjs-inference-engine/rules/owl2rl/owl2rl-eyeling.n3";
const outPath = Deno.args[1] ?? "src/wiki/owl2rl_rules.ts";

const text = Deno.readTextFileSync(rulesPath);
const escaped = text
  .replaceAll("\\", "\\\\")
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${");

const banner = [
  "// Generated by `scripts/bake_owl2rl_rules.ts` — do not edit by hand.",
  "//",
  `// Source: ${rulesPath}`,
  `// ${new TextEncoder().encode(text).length} bytes of OWL 2 RL/RDF rules in`,
  "// Notation3, embedded so the reasoning engine needs no filesystem at run time.",
  "",
].join("\n");

const body = `${banner}export const OWL2RL_N3 = \`${escaped}\`;\n`;
Deno.writeTextFileSync(outPath, body);

console.log(
  `wrote ${outPath} (${text.length} chars of rules, ${body.length} chars module)`,
);
